name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: windows-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Genarate Zip
        run: 
          Compress-Archive -Path *.mjs -DestinationPath deployment.zip -Force
      - name: Deploy para Lambda
        run: aws lambda update-function-code --function-name myFunctionFirstLambda --zip-file fileb://deployment.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}          
